### ISSUE TITLE
Extern "C" functions being re-exported

### ISSUE THREAD

**Issue by jasonish** [mozilla/cbindgen#709]
We have an application that is part Rust, part C.  We use `extern "C" {` to define C functions to Rust. However, `cbindgen` appears to re-export these back out. Short of listing all these in the exclude list, can they still be ignored?

We still want to export Rust functions that are declared extern so our C code can bind to them.

Note: When just `extern {` is used these C functions are not re-exported, but we'd like to use as many `rustfmt` defaults as possible, which rewrites these to `extern "C"`.

**Comment by emilio** [comment]
Can you annotate them on the source with `/// cbindgen:ignore`?

**Comment by jasonish** [comment]
> Can you annotate them on the source with `/// cbindgen:ignore`?

This works on the module level, but not just on an `extern "C" {}` block which would be more useful.

I think the bigger question is why `extern "C" {}` and `extern {}` are treated differently by cbindgen?  And why export functions defined this way anyways, presumably they're in a C header anyways.  Our use case is to create C bindings for a C app to use our Rust code.  We don't need cbindgen to re-export definitions of extern functions.

Happy to look at a fix if there is not reason.

**Comment by emilio** [comment]
I think this works now.

```
extern "C" {
    fn foo();
}

/// cbindgen:ignore
extern "C" {
    fn bar();
}
```

Generates only foo. As for why extern {} and extern "C" {} are different, that's cbindgen being overly restrictive.

**Comment by catenacyber** [comment]
Thanks for the fix, but oops Suricata was not ready and is not compiling anymore with cbindgen 0.27

https://github.com/OISF/suricata/pull/11622 should fix it
