### ISSUE TITLE
C and C++ in same header file?

### ISSUE THREAD

**Issue by vanillajonathan** [mozilla/cbindgen#811]
In other C files I've seen things like:

```h
#ifdef __cplusplus
extern "C" {
#endif

void hello_world(char *greeting);

#ifdef __cplusplus
}
#endif
```

Example: https://github.com/xiallc/PixieSDK/blob/master/sdk/include/pixie16/pixie16.h

Maybe cbindgen could do that?

**Comment by comp500** [comment]
I believe the `cpp_compat` flag does what you're suggesting?

**Comment by vanillajonathan** [comment]
My bad. Yes it does!

Hmm, why isn't this enabled by default?
And why isn't this mentioned in the `template.toml` file?

**Comment by emilio** [comment]
It's in docs.md tho... But yeah would take a patch to mention in template.toml. As for defaults, mostly historical I believe.

**Comment by vanillajonathan** [comment]
Would it be feasible to change the defaults to enable `cpp_compat`?
