### ISSUE TITLE
Release Request for v0.24.4

### ISSUE THREAD

**Issue by ophilli** [mozilla/cbindgen#821]
Hey @emilio, can you please cut a new release on crates.io?

I'd like to have a release that contains https://github.com/eqrion/cbindgen/commit/b6e73017e679caf3b01217e62642d0722a464887

**Comment by ophilli** [comment]
Hey @emilio & @eqrion, could one of y'all please help cut a new release?

**Comment by ophilli** [comment]
Hey @emilio just following up on this again. I'd really love to have a release that contains https://github.com/mozilla/cbindgen/commit/b6e73017e679caf3b01217e62642d0722a464887.

Thanks!

**Comment by emilio** [comment]
Yep, sorry, will try to get to it this today.

**Comment by ophilli** [comment]
Yay, I’m very happy to hear that you’ll try to publish a new release soon! Thanks for taking a look at this @emilio. I know it’s a lot of work to maintain open source and I really appreciate your contributions to the rust community. 😊

**Comment by ophilli** [comment]
Thanks for cutting these releases today Emilio!
