### ISSUE TITLE
Upgrade to clap 4 (getting rid of `atty` as a transitive dependency)

### ISSUE THREAD

**Issue by faern** [mozilla/cbindgen#828]
`cbindgen` is still depending on `clap 3` which in turn depends no `atty`. An unmaintained crate with a [known unsoundness issue](https://rustsec.org/advisories/RUSTSEC-2021-0145.html). We are really trying to get rid of `atty` from our dependency tree, but we also need `cbindgen`. So this issue is about considering an upgrade to `clap 4`.

**Comment by faern** [comment]
Please re-open since you merged a downgrade to clap 3 again in #868

**Comment by micahsnyder** [comment]
Yes please re-open this.
