### ISSUE TITLE
Does this work with async code?

### ISSUE THREAD

**Issue by JonathanWilbur** [mozilla/cbindgen#831]
Does this produce async code that can effectively be used by a C program? I have a library written in Rust that heavily uses async and I would like to use it in a C program if possible.

**Comment by emilio** [comment]
I mean, you can use cbindgen in async code, but you need to effectively box your promises and add APIS to await them from C. So it cannot be transparent, but that's expected given C has no async anything.

Let me know if that is unclear or doesn't answer your question.
