### ISSUE TITLE
Opaque Pointer

### ISSUE THREAD

**Issue by coffeebe4code** [mozilla/cbindgen#835]
I am attempting to turn a non c api compatible pointer back to the caller. 

I just want to treat it as an opaque pointer. I'm not interested in converting all the fields and making a `repr(C)` compatible struct.

Here is an example.

```rust
#[no_mangle]
#[allow(non_snake_case)]
pub extern "C" fn CL_FunctionBuilder_finalize(builder: *mut FunctionBuilder) -> () {
    let ubuilder = unsafe {
        assert!(!builder.is_null());
        core::ptr::read(builder)
    };
    ubuilder.finalize();
}
```

Is there any way to tell cbindgen to honor this?

**Comment by emilio** [comment]
The issue is that cbindgen can't find the `FunctionBuilder` at all, but it does the right thing if you define it:

```
struct FunctionBuilder {}

#[no_mangle]
pub extern "C" fn CL_FunctionBuilder_finalize(builder: *mut FunctionBuilder) -> () {
    let ubuilder = unsafe {
        assert!(!builder.is_null());
        core::ptr::read(builder)
    };
    ubuilder.finalize();
}
```

So this works, it's just a matter of the specific thing you're doing. If `FunctionBuilder` is on a different crate you probably need to let cbindgen run on that crate too?

**Comment by coffeebe4code** [comment]
> If FunctionBuilder is on a different crate you probably need to let cbindgen run on that crate too?

I'm not sure what you mean. FunctionBuilder is defined in another crate. `cranelift`to be precise. It has no C compatible API's I am trying to make it have a C compatible api. However, I don't want to figure out how to make every struct and every property c compatible, and then do a translation from a `#[repr(C)]` struct to `#[repr(Rust)]`. I want FunctionBuilder to be treated as essentially a typedef to a void pointer, and let rust deal with everything on that object.

I know I can make a struct transparent like so.
```rust
#[repr(transparent)]
pub struct CVariable(u32);
```

And this translation is incredibly easy.

I'm just hoping there is a way to do what I am looking for. Please let me know if there is anything close. This is my first time using cbindgen, and the docs didn't quite cover something like this.

**Comment by coffeebe4code** [comment]
Let me know if there is a better way, but I did this to "resolve" my issue. I have yet to get the tool to fully work based on a different issue I have open. But this should theoretically work.

I created a `craneliftc_extra.h` file, and put my typedefs in there, and then specified the include in cbindgen.toml for those extras.

```toml
includes = ["craneliftc_extra.h"]
```

```h
typedef void *FunctionBuilder;
typedef void *UserFuncName;
typedef void *Flags;
typedef void *AbiParam;
typedef void *Builder;
typedef void *Signature;
typedef void *FunctionBuilderContext;
typedef void *Function;
```

**Comment by emilio** [comment]
> @emilio
> 
> > If FunctionBuilder is on a different crate you probably need to let cbindgen run on that crate too?
> 
> I'm not sure what you mean. `FunctionBuilder` is defined in another crate. `cranelift`to be precise. It has no C compatible API's. I am trying to expose a C compatible api. However, I don't want to figure out how to make every struct and every property c compatible, and then do a translation from a `#[repr(C)]` struct to `#[repr(Rust)]`. I want FunctionBuilder to be treated as essentially a typedef to a void pointer, and let rust deal with everything on that object.

Right, I think you can do something like [this](https://searchfox.org/mozilla-central/rev/0c2945ad4769e2d4428c72e6ddd78d60eb920394/servo/ports/geckolib/cbindgen.toml#35-36,38) to make sure cbindgen visits the `cranelift` crate, even tho there's no FFI-compatible thing there.

You probably want `struct FunctionBuilder;` etc rather than `typedef void* FunctionBuilder;` in any case, so that a pointer to `FunctionBuilder` cannot be dereferenced.
