### ISSUE TITLE
Github actions are broken

### ISSUE THREAD

**Issue by jschwe** [mozilla/cbindgen#836]
Error: 
> dtolnay/rust-toolchain@stable, dtolnay/rust-toolchain@1.54, and dtolnay/rust-toolchain@nightly are not allowed to be used in mozilla/cbindgen. Actions in this workflow must be: within a repository that belongs to your Enterprise account, created by GitHub, or matching the following: !/mozilla/**, !mozilla/**, ./**, 10up/wpcs-action@*, aws-actions/*, docker/*, pypa/gh-action-pypi-publish@v1.4.2, slackapi/slack-github-action@*, google-github-actions/*, erlef/setup-beam@v1, yesolutions/mirror-action@*, codecov/codecov-action@*, tj-actions/changed-files@*, tj-actions/glob@*, vmactions/freebsd-vm@v0, actions-rs/toolchain@v1, shivammathur/setup-php@*, EmbarkStudios/*, dependabot/fetch-metadata@*, ilammy/msvc-dev-cmd@v1*, canonical/actions/*, canonical/setup-lxd@*.

@emilio Could you whitelist the `dtolnay` actions?

**Comment by emilio** [comment]
We can probably just use `actions-rs` instead, let me try that (#837).

**Comment by jschwe** [comment]
I would not recommend that, as it is unmaintained and will stop working once github removes NodeJs 12 support (which was supposed to be very soon, unless they postponed it again).

**Comment by emilio** [comment]
I see. I filed [bug 1835662](https://bugzil.la/1835662) to whitelist dtolnay's action, but for now I think we should go with `actions-rs`. Switching back and forth is trivial(ish) anyways.
