### ISSUE TITLE
Build breaks with v0.24.6

### ISSUE THREAD

**Issue by tronical** [mozilla/cbindgen#841]
PR #820 changed the config struct in a way that breaks existing code:

```patch
@@ -1003,6 +1003,8 @@ pub struct Config {
     pub only_target_dependencies: bool,
     /// Configuration options specific to Cython.
     pub cython: CythonConfig,
+    #[serde(skip)]
+    pub(crate) config_path: Option<StdPathBuf>,
 }

 impl Default for Config {
```

Our code initialises `Config` not via `::default()` but like this:

```rust
cbindgen::Config {
        pragma_once: true,
        include_version: true,
        // some more fields here
        ..Default::default()
    }
```

and that causes

```bash
error[E0451]: field `config_path` of struct `Config` is private
  --> api/cpp/cbindgen.rs:83:11
   |
83 |         ..Default::default()
   |           ^^^^^^^^^^^^^^^^^^ field `config_path` is private

```

I can work around this of course by using `Config::default()`, but unfortunately the crate release with this change breaks our existing crate on crates.io that relies on this :-(

**Comment by konsti219** [comment]
Same issue here trying to build https://github.com/fzyzcjy/flutter_rust_bridge . The change in that PR is actually a breaking change but was shipped in a patch version.

https://github.com/rust-lang/rfcs/blob/master/text/1105-api-evolution.md
> Major change: adding a private field when all current fields are public.

**Comment by konsti219** [comment]
@emilio This seems quite urgent.

**Comment by emilio** [comment]
Yep, thanks. Yanked 0.24.6. Sorry for not catching that during review. Will publish 0.25 later this week. Let me know if a 0.24.7 with that change reverted would make someone's life easier.

**Comment by tronical** [comment]
Thanks for the quick reaction and fix!

**Comment by sporksmith** [comment]
I'm confused - it looks like this is still broken (or maybe broken again)? I guess based on the CHANGELOG it was decided to keep this breaking change?

https://github.com/mozilla/cbindgen/commit/80526e72f9109d45da10625e790791fc3a5cc18a
>  * Breaking changes: The `Config` struct now has a private member.
