### ISSUE TITLE
the head file should include #pragma once

### ISSUE THREAD

**Issue by kouzhudong** [mozilla/cbindgen#845]
the head file should include #pragma once

**Comment by jschwe** [comment]
`cbindgen` already has this. You can either set `pragma_once = true` in your cbindgen.toml or if you are using a build script, use [`with_pragma_once(true)`](https://docs.rs/cbindgen/latest/cbindgen/struct.Builder.html#method.with_pragma_once).

**Comment by kouzhudong** [comment]
use [with_pragma_once(true)] 
I solved it with this method.
