### ISSUE TITLE
cpplint warnings: two spaces between code and comments

### ISSUE THREAD

**Issue by vanillajonathan** [mozilla/cbindgen#865]
Consider adding two spaces instead of one space between code and comments in order to avoid [cpplint](https://github.com/cpplint/cpplint) warnings.

> libexample.hpp:101:  At least two spaces is best between code and comments  [whitespace/comments] [2]

```cpp
namespace example {

extern "C" {

} // extern "C"

} // namespace example
```

**Comment by emilio** [comment]
Patch welcome!
