### ISSUE TITLE
I've got an issue with the US State Department and DHS contributing to the code base

### ISSUE THREAD

**Issue by hergljkds** [mozilla/cbindgen#887]
The government does not have a first ammendment right.

**Comment by hergljkds** [comment]
AND... github also specified this note as 887, because they are trying to indicate that it is a 77 attack.

**Comment by hergljkds** [comment]
I think that all government workers should be exterminated from code contributions as they are all rapists.

**Comment by emilio** [comment]
not that I have an issue with it, but I don't see any dhs / .gov email address in the commit logs?

**Comment by hergljkds** [comment]
Haa... yeah, *.gov emails with their contributions?  If they were busted for bastardizing free-press (ie the code base, etc) they would be executed for high treason... they know this, so they use contractors and have also attempted to further their work via their own private resources (hence why government worker's rights are not recovered at the end of the working day).
