### ISSUE TITLE
[BUG] `brew install cbindgen` version mismatch

### ISSUE THREAD

**Issue by mversic** [mozilla/cbindgen#888]
Brew thinks it is installing `0.26.0` but when `cbindgen --version` is `0.24.3`

<img width="1136" alt="image" src="https://github.com/mozilla/cbindgen/assets/45123125/5f416427-1f94-4ab3-9951-8dd24c3ccb12">

**Comment by jschwe** [comment]
Have you checked with `which cbindgen` that the `cbindgen --version` you are calling is really the homebrew installed cbindgen? For me the cbindgen installed via brew correctly reports itself as 0.26.0

**Comment by mversic** [comment]
seems ok now
