### ISSUE TITLE
Correctly parsing c variadics `args: ...`

### ISSUE THREAD

**Issue by darleybarreto** [mozilla/cbindgen#891]
I was looking at how cbindgen is parsing c variadic arguments [here](https://github.com/mozilla/cbindgen/blob/703b53c06f9fe2dbc0193d67626558cfa84a0f62/src/bindgen/ir/ty.rs#L538). Would it be possible to make it c variadic instead of VaList? For instance this function

```rust
func(stream: *mut FILE, fmt: *const c_char, mut args: ...) 
```
Would be exported to a header as
```c
func(FILE * stream, const char * fmt, ...)
```

**Comment by kanru** [comment]
+1 it was broken by #805 
I'd like to generate a definition that is compatible with an existing C definition which uses the `...` syntax.

Note: in 0.24.5 it somehow worked because cbindgen outputs `...` for function pointers

Example

```rust
#[no_mangle]
pub extern "C" fn chewing_set_logger(
    ctx: *mut ChewingContext,
    logger: extern "C" fn(data: *mut c_void, level: c_int, fmt: *const c_char, arg: ...),
    data: *mut c_void,
) {}
```
used to output

```c
void chewing_set_logger(ChewingContext *ctx,
                        void (*logger) (void *data, int level, const char *fmt, ...), void *data);
```
