### ISSUE TITLE
Config (still) has private fields in `0.26`

### ISSUE THREAD

**Issue by virtualritz** [mozilla/cbindgen#908]
See #841 .

This is still broken in `0.26`. This makes `Builder::with_config()` a PITA to use.

```rust
    cbindgen::Builder::new()
        .with_crate(std::env::var("CARGO_MANIFEST_DIR").unwrap())
        .with_config(cbindgen::Config {
            language: cbindgen::Language::C,
            braces: cbindgen::Braces::SameLine,
            cpp_compat: true,
            style: cbindgen::Style::Both,
            ..Default::default()
        })
        .generate()?
        .write_to_file("binding.h");
```

```
error[E0451]: field `config_path` of struct `Config` is private
   --> foo/build.rs:104:15
    |
104 |             ..Default::default()
    |               ^^^^^^^^^^^^^^^^^^ field `config_path` is private
```

**Comment by jschwe** [comment]
`cbindgen` follows cargo semver, so version 0.25 -> 0.26 allows breaking changes. The previous issue was because 0.25.x -> 0.25.y should not contain any breaking changes.

**Comment by virtualritz** [comment]
Basically, this forces one to create a `mut`able `Config::default() ` and then set the resp. fields on that, line by line, then pass it to `with_config()`.

This is neither canonical Rust nor the intended use of the [init-struct-pattern](https://xaeroxe.github.io/init-struct-pattern/) employed here.

**Comment by fzyzcjy** [comment]
I am also seeing this issue when working on https://github.com/fzyzcjy/flutter_rust_bridge. Looking forward to seeing it fixed!

**Comment by virtualritz** [comment]
On that note, the clash between wanting to keep parts of a struct private and this breaking initializiation patterns has been [discussed elsewhere](https://internals.rust-lang.org/t/partial-struct-initialization-with-private-fields/12716).

There is also a related, old [RFC](https://github.com/rust-lang/rfcs/pull/1806).

My point would be that until (or if ever) this is supported by the compiler, if you have a struct that you want to support initializing with the init-struct pattern while keeping some of its fields private, the straightforward option is to make a 2nd struct, just for the pattern. I.e.:

```rust
pub struct Foo {
     pub a: u32,
     pub b: i32
     c: f32,
}

#[derive(Default)]
pub struct FooInit {
     pub a: u32,
     pub b: i32,
}

impl From<FooInit> for Foo {
     ...
}

struct Bar {
     foo: Foo,
     ...
}

impl Bar {
     pub fn with_foo(foo: Foo) {
          ...
     }
}
```

Then you use that:

```rust

let bar = Bar::new()
    .with_foo(FooInit {
        a: 42,
        ..default::Default()
    }.into());
```

**Comment by virtualritz** [comment]
I'm not saying I would do this.

I'd just not have partially private structs. I think the added safety the former provides is dwarfed by the cumbersome workarounds required to keep UX pleasant. See code above.
