### ISSUE TITLE
Not scan file content import by micro include! ?

### ISSUE THREAD

**Issue by luodongseu** [mozilla/cbindgen#909]
I have a rust file named c.rs which import by include! in lib.rs and cbindgen generate c header file cannot include the file content, and I don't know how to resolve it.

lib.rs
```
include!("c.rs");
```

And c.rs content:
```
pub unsafe extern "C" fn m_func() {}
```

**Comment by emilio** [comment]
We can't expand macros by default, see the expand option in the docs for workarounds.

**Comment by emilio** [comment]
For `include!` in particular perhaps we could expand it ourselves tho... Maybe worth a patch if somebody wants to submit it :)
