### ISSUE TITLE
Incorrect (outdated?) `fetch_all_dependencies` config suggestion

### ISSUE THREAD

**Issue by rockboynton** [mozilla/cbindgen#936]
When parsing deps fails I get the following suggestions:

```
Parsing crate `strum_macros`: can't find lib.rs with `cargo metadata`. The crate may be available only on a particular platform, so consider setting `fetch_all_dependencies` in your cbindgen configuration.
```

`fetch_all_dependencies` doesn't appear anywhere in the codebase besides this error message currently.

**Comment by emilio** [comment]
Ugh, yeah, so this is from 93c06c5c9d319f481788c9670700097b4e46d270. The warning mentions the original option name, but it landed with the name flipped (`﻿only_target_dependencies`) and off-by-default, and I overlooked that when reviewing.

So the (bad?) news is that unless you're using `only_target_dependencies=true` that's not the source of the problem.

So:

 * Fixing the warning message seems worth it, but...
 * Your problem probably needs some sort of repro to investigate.

Thanks!

**Comment by rockboynton** [comment]
Hi, @emilio, thank you for looking in to this. 

You're correct that it wasn't actually the source of the problem, and I don't have this issue anymore 🤷🏻‍♂️ so I don't remember the cause...maybe someone else will into a similar issue and can comment, or I will if I see this again

**Comment by emilio** [comment]
Let's close for now, if someone runs into it again we can reopen.
