### ISSUE TITLE
Generate C packed struct

### ISSUE THREAD

**Issue by flaviojs** [mozilla/cbindgen#952]
I can't get cbindgen to generate packed structs.

I was expecting something like:
```rust
#[repr(C, packed)]
pub struct repr_c_packed  {
    pub a: u8,
    pub b: u16,
    pub c: u32,
}
```

to generate the C code:
```C
struct repr_c_packed {
  uint8_t a;
  uint16_t b;
  uint32_t c;
} __attribute__((__packed__));
```

What is the correct way to generate a packed struct? (if needed, I'm willing to implement the feature in cbindgen)

**Comment by emilio** [comment]
We have support for this (#431), is that not working? You need to set the `layout.packed` config tho.

**Comment by flaviojs** [comment]
When I did not see the struct details I was expecting a warning message about the type, like other skipped types.
Searching the issues and reading the docs did not enlighten me about `layout.packed`.

Now I know how to generated the struct details, thanks. :+1:
