### ISSUE TITLE
New cbindgen release?

### ISSUE THREAD

**Issue by penberg** [mozilla/cbindgen#983]
The current 0.26.0 release has a dependency to `atty`, which now has a Github security advisory. The dependency has been removed from the source tree, but it would be great to have a release of cbindgen that projects can switch to.

**Comment by stevenengler** [comment]
As another motivating example, the current cbindgen release depends on syn 1.x, but also depends on serde which requires syn 2.x. This means that cbindgen needs to build syn twice. The most recent Cargo.toml has [already updated](https://github.com/mozilla/cbindgen/commit/aa8ea654e156fd1b8e5b1b755c7b43fe4ea81331) cbindgen to syn 2.x.

**Comment by MacMoneysac666** [comment]
@emilio Hi, it would be great if a new release could be built for this issue. We would need the c string literal #927. Thank you very much!

**Comment by emilio** [comment]
This is done now, real sorry for the lag here (last few months I've been recovering from surgery so with even less free time than usual)
