### ISSUE TITLE
FTBFS firefox and thunderbird with cbindgen 0.27.0

### ISSUE THREAD

**Issue by rautyrauty** [mozilla/cbindgen#998]
I build rpm packages with thunderbird and firefox.
After updating cbindgen in the distribution repository from 0.26.0 to 0.27.0, firefox and thunderbird cannot be built.
I am sending logs to firefox only because the error is the same and they have a common git repository.

The lines with the error from cbindgen:
<pre>
0:29.88 thread 'main' panicked at src/bindgen/config.rs:1125:34:
 0:29.88 called `Result::unwrap()` on an `Err` value: "Couldn't parse config file: TOML parse error at line 363, column 1\n    |\n363 | \"Keyframe\" = \"Keyframe\"\n    | ^\nduplicate key `Keyframe` in table `export.rename`\n."
</pre>

[firefox-cbindgen-0260.log](https://github.com/user-attachments/files/16824903/firefox-cbindgen-0260.log)
[firefox-ftbfs-cbindgen-0270.log](https://github.com/user-attachments/files/16824904/firefox-ftbfs-cbindgen-0270.log)

**Comment by emilio** [comment]
See https://github.com/mozilla/cbindgen/issues/990
